//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new JsonResourceManager("Assistant.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A chat log assistant for GTA World.
        ///
        ///Installed Version: {0} {1}
        ///Resource Directory: {2}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Filter.
        /// </summary>
        internal static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  because the &quot;{0}&quot; directories already exist..
        /// </summary>
        internal static string AlreadyExistingDirectoriesWarning {
            get {
                return ResourceManager.GetString("AlreadyExistingDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to disable the automatic startup function..
        /// </summary>
        internal static string AutoStartDisableError {
            get {
                return ResourceManager.GetString("AutoStartDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to enable the automatic startup function..
        /// </summary>
        internal static string AutoStartEnableError {
            get {
                return ResourceManager.GetString("AutoStartEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature will stop working if you delete or move the parser to a different location..
        /// </summary>
        internal static string AutoStartWarning {
            get {
                return ResourceManager.GetString("AutoStartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while trying to automatically save the chat log.
        ///
        ///Make sure you picked a non-system directory for your backup path..
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurent while moving the backup files to the new directory..
        /// </summary>
        internal static string BackupMoveError {
            get {
                return ResourceManager.GetString("BackupMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Backup: {0}.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic backup has been turned OFF, please set it up again if you wish to use it..
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The automatic backup function will be turned off while the settings dialog is open and the new settings will only be applied once you close the settings dialog.
        ///
        ///Would you like to continue?.
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a non-root directory for your backup directory location..
        /// </summary>
        internal static string BadBackupPath {
            get {
                return ResourceManager.GetString("BadBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a valid backup location or turn automatic backup off..
        /// </summary>
        internal static string BadBackupPathSave {
            get {
                return ResourceManager.GetString("BadBackupPathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiveM does not require a game directory to capture the local GTAW chat..
        /// </summary>
        internal static string BadDirectoryPath {
            get {
                return ResourceManager.GetString("BadDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b.
        /// </summary>
        internal static string BetaShort {
            get {
                return ResourceManager.GetString("BetaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters and {1} lines.
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current time: {0}.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local FiveM GTAW chat is captured automatically..
        /// </summary>
        internal static string DirectoryFinder {
            get {
                return ResourceManager.GetString("DirectoryFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking the local FiveM GTAW chat..
        /// </summary>
        internal static string DirectoryFinderError {
            get {
                return ResourceManager.GetString("DirectoryFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t detect the local FiveM GTAW chat. Open FiveM and join the server first..
        /// </summary>
        internal static string DirectoryFinderNotFound {
            get {
                return ResourceManager.GetString("DirectoryFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information (First Start).
        /// </summary>
        internal static string DirectoryFinderTitle {
            get {
                return ResourceManager.GetString("DirectoryFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://face.gta.world/.
        /// </summary>
        internal static string FacebrowserLink {
            get {
                return ResourceManager.GetString("FacebrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forum.gta.world/en/index.php?/topic/7690-chat-logs/.
        /// </summary>
        internal static string FeatureShowcaseLink {
            get {
                return ResourceManager.GetString("FeatureShowcaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to delete the file..
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only have one word, number, or valid name pair on each line if you want to filter your chat log.
        ///Example: Boat, $500, John, John Doe or John_Doe.
        /// </summary>
        internal static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        ///
        ///Make sure you only have one word, number, or valid name pair on each line.
        ///Example: Boat, $500, John, John Doe or John_Doe.
        /// </summary>
        internal static string FilterHintNoMatches {
            get {
                return ResourceManager.GetString("FilterHintNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more words were skipped during the filtering operation because they are not in a valid format.
        ///
        ///Make sure you only have one word, number, or valid name pair on each line.
        ///Example: Boat, $500, John, John Doe or John_Doe.
        /// </summary>
        internal static string FilterHintSkipped {
            get {
                return ResourceManager.GetString("FilterHintSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat log{0} loaded{1}.
        /// </summary>
        internal static string FilterLogStatus {
            get {
                return ResourceManager.GetString("FilterLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while reading the selected file..
        /// </summary>
        internal static string FilterReadError {
            get {
                return ResourceManager.GetString("FilterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://forum.gta.world/en/.
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back up the chat log automatically while the game is running (every {0} {1}).
        /// </summary>
        internal static string IntervalHint {
            get {
                return ResourceManager.GetString("IntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. (recommended).
        /// </summary>
        internal static string IntervalRecommended {
            get {
                return ResourceManager.GetString("IntervalRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local FiveM GTAW chat is unavailable..
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open FiveM and join GTAW before enabling automatic backup..
        /// </summary>
        internal static string InvalidDirectoryPathBackup {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open FiveM and join GTAW before filtering the chat log..
        /// </summary>
        internal static string InvalidDirectoryPathFilter {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen language will be used to extract the chat log from the correct server.
        ///
        ///This means that if you chose English, you will only be able to parse the chat log generated from the English server. You will need to change the language of the application if you wish to parse other chat logs..
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at {0}.
        /// </summary>
        internal static string LoadedAt {
            get {
                return ResourceManager.GetString("LoadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.178.79.228_22005.
        /// </summary>
        internal static string MainIP {
            get {
                return ResourceManager.GetString("MainIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing the parser will prevent the automatic backups from happening.
        ///
        ///Would you like to minimize the parser to the system tray instead?.
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to move all of your existing backup files to the new directory?.
        /// </summary>
        internal static string MoveBackups {
            get {
                return ResourceManager.GetString("MoveBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple GTA World resource directories were found. It is advised you use a single IP to connect to the server and delete the other resource directory.
        ///
        ///Keep either &quot;{0}&quot; or &quot;{1}&quot;..
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  not.
        /// </summary>
        internal static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the GTA World chat log..
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t loaded a chat log yet..
        /// </summary>
        internal static string NoChatLogLoaded {
            get {
                return ResourceManager.GetString("NoChatLogLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates could be found.
        ///Try checking your internet connection or increasing the update check timeout in the settings window.
        ///
        ///Installed Version: {0}.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t filtered anything yet..
        /// </summary>
        internal static string NothingFiltered {
            get {
                return ResourceManager.GetString("NothingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not move any directories to the new location.
        /// </summary>
        internal static string NothingMovedWarning {
            get {
                return ResourceManager.GetString("NothingMovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t parsed anything yet..
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t entered any words to filter in.
        ///
        ///Use the simple filter if you don&apos;t want to filter for words..
        /// </summary>
        internal static string NoWordsToFilter {
            get {
                return ResourceManager.GetString("NoWordsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old format was detected while parsing the chat log and it is advised you delete it and all other scripts that didn&apos;t update correcly.
        ///
        ///Would you like to delete these files?
        ///(The chat log file will be parsed before deletion).
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to open the documentation page for the chat log parser found on the GTA World forums?.
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance is already running, check your taskbar or task manager..
        /// </summary>
        internal static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while parsing the chat log..
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only moved the &quot;{0}&quot; directories to the new location.
        /// </summary>
        internal static string PartialMoveWarning {
            get {
                return ResourceManager.GetString("PartialMoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AdvGTAW/GTAW-Log-Parser.
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/AdvGTAW/GTAW-Log-Parser/releases.
        /// </summary>
        internal static string ReleasesLink {
            get {
                return ResourceManager.GetString("ReleasesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version of the chat log parser.
        ///
        ///Installed Version: {0}.
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same chat capture has been backed up {0} or more times. FiveM may be disconnected from GTAW or its local chat is unavailable.
        ///
        ///Open FiveM and rejoin the server, then try again..
        /// </summary>
        internal static string SameHashWarning {
            get {
                return ResourceManager.GetString("SameHashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save the file..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.gta.world_22005.
        /// </summary>
        internal static string SecondaryIP {
            get {
                return ResourceManager.GetString("SecondaryIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondPlural {
            get {
                return ResourceManager.GetString("SecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string SecondSingular {
            get {
                return ResourceManager.GetString("SecondSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings will only be applied once you close the settings dialog..
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Filter.
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully parsed and backed up chat log to {0}.
        /// </summary>
        internal static string SuccessfulBackup {
            get {
                return ResourceManager.GetString("SuccessfulBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parser needs to restart in order to switch to the selected server.
        ///
        ///Would you like to apply the changes and restart the application now?.
        /// </summary>
        internal static string SwitchServer {
            get {
                return ResourceManager.GetString("SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ucp.gta.world/.
        /// </summary>
        internal static string UCPLink {
            get {
                return ResourceManager.GetString("UCPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}..
        /// </summary>
        internal static string UpdateAbortTime {
            get {
                return ResourceManager.GetString("UpdateAbortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the chat log parser is now available on GitHub.
        ///
        ///Installed Version: {0}
        ///Available Version: {1}
        ///
        ///Would you like to visit the releases page now?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }

        internal static string SettingsTitleBar {
            get {
                return ResourceManager.GetString("SettingsTitleBar", resourceCulture);
            }
        }

        internal static string SettingsOther {
            get {
                return ResourceManager.GetString("SettingsOther", resourceCulture);
            }
        }

        internal static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }

        internal static string SettingsDisableForumsIcon {
            get {
                return ResourceManager.GetString("SettingsDisableForumsIcon", resourceCulture);
            }
        }

        internal static string SettingsDisableFacebrowserIcon {
            get {
                return ResourceManager.GetString("SettingsDisableFacebrowserIcon", resourceCulture);
            }
        }

        internal static string SettingsDisableUCPIcon {
            get {
                return ResourceManager.GetString("SettingsDisableUCPIcon", resourceCulture);
            }
        }

        internal static string SettingsDisableReleasesIcon {
            get {
                return ResourceManager.GetString("SettingsDisableReleasesIcon", resourceCulture);
            }
        }

        internal static string SettingsDisableProjectIcon {
            get {
                return ResourceManager.GetString("SettingsDisableProjectIcon", resourceCulture);
            }
        }

        internal static string SettingsDisableInfoPopups {
            get {
                return ResourceManager.GetString("SettingsDisableInfoPopups", resourceCulture);
            }
        }

        internal static string SettingsDisableWarningPopups {
            get {
                return ResourceManager.GetString("SettingsDisableWarningPopups", resourceCulture);
            }
        }

        internal static string SettingsDisableErrorPopups {
            get {
                return ResourceManager.GetString("SettingsDisableErrorPopups", resourceCulture);
            }
        }

        internal static string SettingsAbortCheckPrefix {
            get {
                return ResourceManager.GetString("SettingsAbortCheckPrefix", resourceCulture);
            }
        }

        internal static string SettingsIgnoreBeta {
            get {
                return ResourceManager.GetString("SettingsIgnoreBeta", resourceCulture);
            }
        }

        internal static string SettingsFollowSystemColor {
            get {
                return ResourceManager.GetString("SettingsFollowSystemColor", resourceCulture);
            }
        }

        internal static string SettingsFollowSystemMode {
            get {
                return ResourceManager.GetString("SettingsFollowSystemMode", resourceCulture);
            }
        }

        internal static string SettingsDarkMode {
            get {
                return ResourceManager.GetString("SettingsDarkMode", resourceCulture);
            }
        }

        internal static string AutoParse {
            get {
                return ResourceManager.GetString("AutoParse", resourceCulture);
            }
        }

        internal static string SectionTranslation {
            get {
                return ResourceManager.GetString("SectionTranslation", resourceCulture);
            }
        }

        internal static string TranslationEnabled {
            get {
                return ResourceManager.GetString("TranslationEnabled", resourceCulture);
            }
        }

        internal static string TargetLanguage {
            get {
                return ResourceManager.GetString("TargetLanguage", resourceCulture);
            }
        }

        internal static string TranslationProvider {
            get {
                return ResourceManager.GetString("TranslationProvider", resourceCulture);
            }
        }

        internal static string TranslationProviderGoogle {
            get {
                return ResourceManager.GetString("TranslationProviderGoogle", resourceCulture);
            }
        }

        internal static string TranslationProviderDeepSeek {
            get {
                return ResourceManager.GetString("TranslationProviderDeepSeek", resourceCulture);
            }
        }

        internal static string DeepSeekApiKey {
            get {
                return ResourceManager.GetString("DeepSeekApiKey", resourceCulture);
            }
        }

        internal static string DeepSeekModel {
            get {
                return ResourceManager.GetString("DeepSeekModel", resourceCulture);
            }
        }

        internal static string TranslationDisplayMode {
            get {
                return ResourceManager.GetString("TranslationDisplayMode", resourceCulture);
            }
        }

        internal static string TranslationDisplayAppend {
            get {
                return ResourceManager.GetString("TranslationDisplayAppend", resourceCulture);
            }
        }

        internal static string TranslationDisplayReplace {
            get {
                return ResourceManager.GetString("TranslationDisplayReplace", resourceCulture);
            }
        }

        internal static string TranslationPrompt {
            get {
                return ResourceManager.GetString("TranslationPrompt", resourceCulture);
            }
        }

        internal static string TranslationStyle {
            get {
                return ResourceManager.GetString("TranslationStyle", resourceCulture);
            }
        }

        internal static string TranslationStyleCasual {
            get {
                return ResourceManager.GetString("TranslationStyleCasual", resourceCulture);
            }
        }

        internal static string TranslationStyleFormal {
            get {
                return ResourceManager.GetString("TranslationStyleFormal", resourceCulture);
            }
        }

        internal static string TranslationStyleLiterary {
            get {
                return ResourceManager.GetString("TranslationStyleLiterary", resourceCulture);
            }
        }

        internal static string TranslationBulkHotkey {
            get {
                return ResourceManager.GetString("TranslationBulkHotkey", resourceCulture);
            }
        }

        internal static string AutoTranslate {
            get {
                return ResourceManager.GetString("AutoTranslate", resourceCulture);
            }
        }

        internal static string AutoTranslateHotkey {
            get {
                return ResourceManager.GetString("AutoTranslateHotkey", resourceCulture);
            }
        }

        internal static string ShowGameToasts {
            get {
                return ResourceManager.GetString("ShowGameToasts", resourceCulture);
            }
        }

        internal static string ToastPrefix {
            get {
                return ResourceManager.GetString("ToastPrefix", resourceCulture);
            }
        }

        internal static string ToastTranslatorOn {
            get {
                return ResourceManager.GetString("ToastTranslatorOn", resourceCulture);
            }
        }

        internal static string ToastTranslatorOff {
            get {
                return ResourceManager.GetString("ToastTranslatorOff", resourceCulture);
            }
        }

        internal static string ToastAutoOn {
            get {
                return ResourceManager.GetString("ToastAutoOn", resourceCulture);
            }
        }

        internal static string ToastAutoOff {
            get {
                return ResourceManager.GetString("ToastAutoOff", resourceCulture);
            }
        }

        internal static string ToastBulkDone {
            get {
                return ResourceManager.GetString("ToastBulkDone", resourceCulture);
            }
        }

        internal static string TranslationProviderDeepL {
            get {
                return ResourceManager.GetString("TranslationProviderDeepL", resourceCulture);
            }
        }

        internal static string DeepLApiKey {
            get {
                return ResourceManager.GetString("DeepLApiKey", resourceCulture);
            }
        }

        internal static string SendDeepLApiKey {
            get {
                return ResourceManager.GetString("SendDeepLApiKey", resourceCulture);
            }
        }

        internal static string TranslationProviderDoubao {
            get {
                return ResourceManager.GetString("TranslationProviderDoubao", resourceCulture);
            }
        }

        internal static string TranslationProviderDoubaoFree {
            get {
                return ResourceManager.GetString("TranslationProviderDoubaoFree", resourceCulture);
            }
        }

        internal static string DoubaoApiKey {
            get {
                return ResourceManager.GetString("DoubaoApiKey", resourceCulture);
            }
        }

        internal static string DoubaoModel {
            get {
                return ResourceManager.GetString("DoubaoModel", resourceCulture);
            }
        }

        internal static string DoubaoFreeEndpoint {
            get {
                return ResourceManager.GetString("DoubaoFreeEndpoint", resourceCulture);
            }
        }

        internal static string SendDoubaoApiKey {
            get {
                return ResourceManager.GetString("SendDoubaoApiKey", resourceCulture);
            }
        }

        internal static string SendDoubaoModel {
            get {
                return ResourceManager.GetString("SendDoubaoModel", resourceCulture);
            }
        }

        internal static string SendDoubaoFreeEndpoint {
            get {
                return ResourceManager.GetString("SendDoubaoFreeEndpoint", resourceCulture);
            }
        }

        internal static string SettingsPageTranslation {
            get {
                return ResourceManager.GetString("SettingsPageTranslation", resourceCulture);
            }
        }

        internal static string SourceLanguage {
            get {
                return ResourceManager.GetString("SourceLanguage", resourceCulture);
            }
        }

        internal static string SourceLanguageAuto {
            get {
                return ResourceManager.GetString("SourceLanguageAuto", resourceCulture);
            }
        }

        internal static string SendTranslationEnabled {
            get {
                return ResourceManager.GetString("SendTranslationEnabled", resourceCulture);
            }
        }

        internal static string SendTranslationHotkey {
            get {
                return ResourceManager.GetString("SendTranslationHotkey", resourceCulture);
            }
        }

        internal static string SendOverlayTitle {
            get {
                return ResourceManager.GetString("SendOverlayTitle", resourceCulture);
            }
        }

        internal static string SendOverlaySend {
            get {
                return ResourceManager.GetString("SendOverlaySend", resourceCulture);
            }
        }

        internal static string SendOverlayCancel {
            get {
                return ResourceManager.GetString("SendOverlayCancel", resourceCulture);
            }
        }

        internal static string SendOverlayApply {
            get {
                return ResourceManager.GetString("SendOverlayApply", resourceCulture);
            }
        }

        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        internal static string BackupSettingsTitle {
            get {
                return ResourceManager.GetString("BackupSettingsTitle", resourceCulture);
            }
        }

        internal static string BackupPathLabel {
            get {
                return ResourceManager.GetString("BackupPathLabel", resourceCulture);
            }
        }

        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }

        internal static string BackupAutomatically {
            get {
                return ResourceManager.GetString("BackupAutomatically", resourceCulture);
            }
        }

        internal static string BackupEveryPrefix {
            get {
                return ResourceManager.GetString("BackupEveryPrefix", resourceCulture);
            }
        }

        internal static string RemoveTimestampsFromBackup {
            get {
                return ResourceManager.GetString("RemoveTimestampsFromBackup", resourceCulture);
            }
        }

        internal static string SuppressNotifications {
            get {
                return ResourceManager.GetString("SuppressNotifications", resourceCulture);
            }
        }

        internal static string AlwaysCloseToTray {
            get {
                return ResourceManager.GetString("AlwaysCloseToTray", resourceCulture);
            }
        }

        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }

        internal static string WarnOnSameHash {
            get {
                return ResourceManager.GetString("WarnOnSameHash", resourceCulture);
            }
        }

        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }

        internal static string LoadUnparsed {
            get {
                return ResourceManager.GetString("LoadUnparsed", resourceCulture);
            }
        }

        internal static string BrowseForParsed {
            get {
                return ResourceManager.GetString("BrowseForParsed", resourceCulture);
            }
        }

        internal static string CriterionLocal {
            get {
                return ResourceManager.GetString("CriterionLocal", resourceCulture);
            }
        }

        internal static string CriterionOOC {
            get {
                return ResourceManager.GetString("CriterionOOC", resourceCulture);
            }
        }

        internal static string CriterionEmote {
            get {
                return ResourceManager.GetString("CriterionEmote", resourceCulture);
            }
        }

        internal static string CriterionAction {
            get {
                return ResourceManager.GetString("CriterionAction", resourceCulture);
            }
        }

        internal static string CriterionRadio {
            get {
                return ResourceManager.GetString("CriterionRadio", resourceCulture);
            }
        }

        internal static string CriterionPM {
            get {
                return ResourceManager.GetString("CriterionPM", resourceCulture);
            }
        }

        internal static string CriterionAds {
            get {
                return ResourceManager.GetString("CriterionAds", resourceCulture);
            }
        }

        internal static string CriterionOther {
            get {
                return ResourceManager.GetString("CriterionOther", resourceCulture);
            }
        }

        internal static string RemoveTimestamps {
            get {
                return ResourceManager.GetString("RemoveTimestamps", resourceCulture);
            }
        }

        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }

        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }

        internal static string WordsToFilter {
            get {
                return ResourceManager.GetString("WordsToFilter", resourceCulture);
            }
        }

        internal static string FirstnameLastname {
            get {
                return ResourceManager.GetString("FirstnameLastname", resourceCulture);
            }
        }

        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }

        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }

        internal static string TooltipSettings {
            get {
                return ResourceManager.GetString("TooltipSettings", resourceCulture);
            }
        }

        internal static string TooltipProject {
            get {
                return ResourceManager.GetString("TooltipProject", resourceCulture);
            }
        }

        internal static string TooltipReleases {
            get {
                return ResourceManager.GetString("TooltipReleases", resourceCulture);
            }
        }

        internal static string TooltipUCP {
            get {
                return ResourceManager.GetString("TooltipUCP", resourceCulture);
            }
        }

        internal static string TooltipFacebrowser {
            get {
                return ResourceManager.GetString("TooltipFacebrowser", resourceCulture);
            }
        }

        internal static string TooltipForums {
            get {
                return ResourceManager.GetString("TooltipForums", resourceCulture);
            }
        }

        internal static string MenuCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuCheckForUpdates", resourceCulture);
            }
        }

        internal static string MenuBackupSettings {
            get {
                return ResourceManager.GetString("MenuBackupSettings", resourceCulture);
            }
        }

        internal static string MenuFilterChatLog {
            get {
                return ResourceManager.GetString("MenuFilterChatLog", resourceCulture);
            }
        }

        internal static string MenuChangeServer {
            get {
                return ResourceManager.GetString("MenuChangeServer", resourceCulture);
            }
        }

        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }

        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }

        internal static string CheckForUpdatesAutomatically {
            get {
                return ResourceManager.GetString("CheckForUpdatesAutomatically", resourceCulture);
            }
        }

        internal static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }

        internal static string TrayText {
            get {
                return ResourceManager.GetString("TrayText", resourceCulture);
            }
        }

        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
    }
}
